services:

  user-service:
    build: user-service
    image: user-service:latest
    container_name: user-service
    ports:
      - "802:902"
    depends_on:
      users-db:
        condition: service_healthy
      mongo-users-db:
        condition: service_started
    networks:
      - task-manager-net
      - user-service-net
    environment:
      - POSTGRES_DB=users_db
      - POSTGRES_HOST=users-db:5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres

      - MONGO_URI=mongodb://appuser:apppassword@mongo-users-db:27017/userdb?authSource=userdb
      - MONGO_DB=userdb
      - MONGO_GRIDFS_BUCKET=users

      - JWT_ISSUER=user-service
      - JWT_ACCESS_EXPIRATION_MS=900000
      - JWT_REFRESH_EXPIRATION_MS=1800000
      - JWT_AUDIENCE=user-service-api

      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=900
      - LIQUIBASE_ENABLE=true
      - LOGSTASH=logstash:50000

      - JWT_ACCESS_PUBLIC_KEY=classpath:keys/access_public.pem
      - JWT_REFRESH_PUBLIC_KEY=classpath:keys/refresh_public.pem
      - JWT_ACCESS_PRIVATE_KEY=classpath:keys/access_private.pem
      - JWT_REFRESH_PRIVATE_KEY=classpath:keys/refresh_private.pem

      - KAFKA_USER_CREATED_TOPIC=user-service.user-created-notification
      - KAFKA_USER_UPDATED_TOPIC=user-service.user-updated-notification
      - KAFKA_USER_DELETED_TOPIC=user-service.user-deleted-notification

      - KAFKA_BOOTSTRAP_SERVER_1=kafka1:9092
      - KAFKA_BOOTSTRAP_SERVER_2=kafka2:9092
      - KAFKA_BOOTSTRAP_SERVER_3=kafka3:9092

  users-db:
    image: postgres:18-alpine
    container_name: users-db
    ports:
      - "5444:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - user-service-net
    logging:
      driver: json-file  # Логи в JSON-формате
      options:
        labels: "env=dev,name=database"  # Лейблы
        tag: "{{.Name}}"  # Доп. теги для логов
    labels:
      - "env=dev"        # Лейблы для контейнера
      - "name={{.Name}}"

  mongo-users-db:
    build:
      context: DockerConfig/mongo
      # Запуск из докерфайла чтобы запустить скрипты на созданик БД и бакета GridFS
      dockerfile: Dockerfile
      #dockerfile: DockerConfig/mongo/Dockerfile
    container_name: mongo-users-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: userdb
    networks:
      - user-service-net
      - mongo-net
    volumes:
      - mongo-users-storage:/var/lib/mongo/data
      - ./mongo-logs:/var/log/mongodb
    # Только для разработки!
    privileged: true
    # ----------------
    healthcheck:
      test: |
        echo 'db.runCommand("ping").ok' | mongosh localhost:27017/admin -u admin -p admin --authenticationDatabase admin --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      nofile:
        soft: 64000
        hard: 64000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "env=dev,name={{.Name}}"
        tag: "{{.Name}}"

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    restart: unless-stopped
    networks:
      - mongo-net
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin@mongo-users-db:27017/userdb?authSource=admin"
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      mongo-users-db:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
        labels: "env=dev,name={{.Name}}"
        tag: "{{.Name}}"

  discovery-server:
    build: discovery-server
    image: discovery-server:latest
    container_name: discovery-server
    ports:
      - "800:900"
    networks:
      - task-manager-net
    environment:
      - DISCOVERY_SERVER_HOST=discovery-server
      - DISCOVERY_SERVER_PORT=900
      - LOGSTASH=logstash:50000

volumes:
  postgres_data:
  mongo-users-storage: {}

networks:
  task-manager-net:
    driver: bridge
    external: true
  mongo-net:
    driver: bridge
    external: true
  user-service-net:
    driver: bridge