spring:
  application:
    name: kafka-starter

properties:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29091}, ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}, ${KAFKA_BOOTSTRAP_SERVER:localhost:29093}
    producer:
      topic: test-topic
      idempotence-enabled: true
      acks: -1
      retries: 5
      retry-backoff-ms: 2000
      delivery-timeout-ms: 120000
      request-timeout-ms: 30000
      max-in-flight-requests: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      topic: test-topic
      group-id: my-group
      max-poll-records: 1000
      max-poll-interval-ms: 600000
      session-timeout-ms: 15000
      heartbeat-interval-ms: 5000
      fetch-max-bytes: 52428800
      auto-commit-enabled: true
      auto-commit-interval-ms: 5000
      auto-offset-reset: earliest
      retry-backoff-ms: 2000
      max-retries: 5

    min.insync.replicas: 1
